"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var ViewEngines;
(function (ViewEngines) {
    ViewEngines["atpl"] = "atpl";
    ViewEngines["dot"] = "dot";
    ViewEngines["dust"] = "dust";
    ViewEngines["eco"] = "eco";
    ViewEngines["ejs"] = "ejs";
    ViewEngines["ect"] = "ect";
    ViewEngines["haml"] = "haml";
    ViewEngines["hamlet"] = "hamlet";
    ViewEngines["handlebars"] = "handlebars";
    ViewEngines["hogan"] = "hogan";
    ViewEngines["htmling"] = "htmling";
    ViewEngines["jade"] = "jade";
    ViewEngines["jazz"] = "jazz";
    ViewEngines["jqtpl"] = "jqtpl";
    ViewEngines["just"] = "just";
    ViewEngines["liquid"] = "liquid";
    ViewEngines["liquor"] = "liquor";
    ViewEngines["lodash"] = "lodash";
    ViewEngines["mote"] = "mote";
    ViewEngines["mustache"] = "mustache";
    ViewEngines["nunjucks"] = "nunjucks";
    ViewEngines["pug"] = "pug";
    ViewEngines["qejs"] = "qejs";
    ViewEngines["ractive"] = "ractive";
    ViewEngines["react"] = "react";
    ViewEngines["swig"] = "swig";
    ViewEngines["templayed"] = "templayed";
    ViewEngines["toffee"] = "toffee";
    ViewEngines["underscore"] = "underscore";
    ViewEngines["walrus"] = "walrus";
    ViewEngines["whiskers"] = "whiskers0";
})(ViewEngines = exports.ViewEngines || (exports.ViewEngines = {}));
//# sourceMappingURL=enums.js.map